.gitattributes, .qgis-plugin-ci, .travis.yml
* Create the GitHub release automatically
* Update `plugins.xml` to give to the client to update their plugin
=> automatic deployment from travis

gestion_base_adresse/definitions/__init__.py, gestion_base_adresse/definitions/variables.py, gestion_base_adresse/processing/data/load_layers.py, gestion_base_adresse/processing/processing_tools.py, gestion_base_adresse/processing/provider.py, gestion_base_adresse/processing/structure/create_database_structure.py, gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/processing/tools/__init__.py, gestion_base_adresse/processing/tools/configure_project.py
=> add configure project algorithm

gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/test/test_load_structure.py
* Use QgsProcessingException for stoping a Processing algorithm.
Fix #20
=> when upgrading database, set the plugin version at the end

gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.2.9.sql, gestion_base_adresse/resources/qml/voie.qml
Ce PR accompagne le PR du module qui permet l'export des voies à délibérer.
=> ajout trigger et trigger function pour les voie a deliberer

gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.2.9.sql, gestion_base_adresse/resources/qml/document.qml
PR qui contient une modif de la base de données et un nouveau fichier qml pour la couche document
=> import de documents

.docker/install_migrate_generate.sh, .docker/pg_service.conf, .docker/reformat_sql_install.sh, .travis.yml, Makefile, gestion_base_adresse/install/sql/README.md, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql
Fix #31 
Test we can notice a difference between a fresh install and an old install with migrations
=> Run migrations versus fresh install

.docker/docker-compose.yml, .docker/exec.sh, .docker/install_db.sh, .docker/install_migrate_generate.sh, .docker/reformat_sql_install.sh, .docker/schemaspy.properties, .docker/schemaspy.sh, Makefile
This adds a new Makefile command to generate schemaspy documentation
Next step is to generate the docs on a git tag on travis ;-)
=> add schemaspy Makefile command

Makefile, README.md, gestion_base_adresse/metadata.txt, gestion_base_adresse/processing/structure/create_database_structure.py, gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/test/test_load_structure.py
Following the discussions this morning
=> use migrations number for the version in metadata table

gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.2.9.sql, gestion_base_adresse/test/test_execute_functions.py
Ajout de l'export SNA au format ZIP.
Ajout des test correspondant aux issues #28 et #36
=> Export zip

gestion_base_adresse/test/base_test_database.py, gestion_base_adresse/test/test_functions_without_data.py
Related to #49 
Tests might need a database structure but without test data
CC @drillinP @rldhont Do you want this?
=> add a test case for database without data

gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.3.0.sql, gestion_base_adresse/test/test_execute_functions.py
Correction des fonctions trigger pour l'insertion et la mise à jour des points adresses.
A l'aide des tests, je pense couvrir l'ensemble des cas d'insertion et de mise à jour.
=> Fix sql trigger point adresse

.docker/docker-compose-base.yml, .docker/docker-compose-qgis.yml, .docker/install_db.sh, .docker/install_migrate_generate.sh, .docker/reformat_sql_install.sh, .docker/schemaspy.sh, .docker/start.sh, .docker/stop.sh, .github/push_to_github.sh, .travis.yml, Makefile, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql
* Do not load QGIS container when we can skip it
* Generate schemaspy after a release
=> Update docker-compose architecture

.docker/docker-compose-base.yml, .docker/install_migrate_generate.sh, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql
@mdouchin Est-ce que cela est OK ?
CF le PR de @Enola-sengeissen https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin/pull/13
sur les séquences
Bon en fait, c'est plus du 10.6 malgré le tag. C'est mieux comme ca.
=> bump PostgreSQL version to 10.6

gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.3.1.sql, gestion_base_adresse/test/test_execute_functions.py
=> Fix bug de suppression des voies

CHANGELOG.md, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.5.0.sql, gestion_base_adresse/test/test_execute_functions.py
Update du trigger pour calcul de point apres validation
=> updtae trigger

gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql
* Tests - update to latest docker Postgis image ID
=> Tests - update to latest docker Postgis image ID

gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.6.0.sql
Suite aux demandent du client j'ai modifié la vue export_bal
Ticket: https://github.com/3liz/lizmap-adresse-module/issues/21
=> Update export_bal view and vue_com view

gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.6.0.sql, gestion_base_adresse/processing/data/data_parcelle.py, gestion_base_adresse/processing/data/load_styles.py, gestion_base_adresse/processing/provider.py, gestion_base_adresse/resources/composer/certificat_numerotation.qpt
Partie concernant les certificats de numérotation. Script qui initialise la table adresse.parcelle et créer toutes les vues nécessaires.
=> Certificat num

docs/README.md, docs/index.html, docs/processing/README.md, docs/processing/index.html, docs/user_guide/README.md, docs/user_guide/index.html
J'ai refait un PR suite à la maj du submodule pour tout avoir au propre
=> Update Html Doc

gestion_base_adresse/processing/structure/create_database_structure.py, gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/test/base_test_database.py, gestion_base_adresse/test/test_load_structure.py
=> Choose database CRS

gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_0.7.0.sql, gestion_base_adresse/processing/data/load_layers.py, gestion_base_adresse/test/test_execute_functions.py, gestion_base_adresse/test/test_load_structure.py
* Ticket : #86
* Mise à jour de la vue export_bal:
* Ajout d'un préfixe `v_`
* Renommage du champ `date_derniere_maj` en `date_der_maj`
* Update nom de la vue dans les tests
=> Update view export_bal

gestion_base_adresse/processing/data/data_parcelle.py
* Ticket : #87 
* Mise à jour de l'algorithme data_parcelle.py:
* Choix de remplir ou non la table adresse.parcelle
* Changement du préfixe des vues concernées pas ce script
=> Update script data_parcelle

docs/index.md, mkdocs.yml
=> Adding diagram in doc

.docker/docker-compose-qgis.yml, .docker/install_db.sh, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/install/sql/export_database_structure_to_SQL.sh, gestion_base_adresse/metadata.txt, gestion_base_adresse/processing/data/data_parcelle.py, gestion_base_adresse/processing/data/load_layers.py, gestion_base_adresse/processing/provider.py, gestion_base_adresse/processing/structure/base.py, gestion_base_adresse/processing/structure/create_database_structure.py, gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/test/base_test_database.py, gestion_base_adresse/test/data/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/test/data/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/test/data/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/test/data/install/sql/adresse/40_INDEX.sql, gestion_base_adresse/test/data/install/sql/adresse/50_TRIGGER.sql, gestion_base_adresse/test/data/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/test/data/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/test/test_load_structure.py
* Update the  plugin to work with QGIS >= 31000 and switch to use the new database API 
Easier to start by this plugin than https://github.com/3liz/qgis-lizsync-plugin/pull/19
=> Postgis - use the new QGIS Database API

gestion_base_adresse/test/test_migration.py
* Ticket : #106 
* Ajout des tests transactions sur les fichiers sql d'installation de la base de données
=> Add test transactions for sql file

gestion_base_adresse/processing/tools/configure_project.py
* Ticket : fix #112 
* Modification de la définition des paramètres sur le script de configuration du projet concernant les variables des couches de voie et de point.
=> Reverse variables between two layers in configure project script

CHANGELOG.md, gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_1.0.0.sql
* Ticket : #130 
* Modification  de la fonction `get_parcelle` pour renvoyer uniquement 1 seule valeur.
=> Function get_parcelle: retour unique

CHANGELOG.md, gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_1.0.0.sql
* Ticket : #133 
* Remplacement des `charater varying` par `text`
=> Modification des types des champs

gestion_base_adresse/install/sql/adresse/20_TABLE_SEQUENCE_DEFAULT.sql, gestion_base_adresse/install/sql/adresse/60_CONSTRAINT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_1.0.0.sql, gestion_base_adresse/processing/data/data_parcelle.py
* Ticket : #136 #137 
* Modification de la requête pour mettre à jour la table `adresse.parcelle` en utilisant `INSERT .... ON CONFLICT .... DO...`
* Modification de la récupération de l'identifiant parcelle lors de l'`INSERT`
* Ajout d'une requête `DELETE` pour virer des parcelles pour lesquelles l'identifiant n'existerait plus
* Modification de la description de l'algo
=> Modification de l'algorithme data_parcelle.py

CHANGELOG.md, gestion_base_adresse/processing/data/data_parcelle.py, gestion_base_adresse/processing/data/refresh_view.py, gestion_base_adresse/processing/provider.py, setup.cfg
* Ticket : fix #142 
* Add index on the view, to use `CONCURRENTLY`
* Change view v_certificat to be materialized
=> SQL - Change view v_certificat to be materialized

gestion_base_adresse/processing/data/data_parcelle.py
* SQL - Add LIMIT 1 with ORDER BY distance  when intersecting point and parcelle
Manque le cas si il n'y a pas de parcelle sous le point adresse en question. Ou alors considère-t-on ca un problème dans les données ?
Souhaites-t-on le ST_DWithin avec une distance arbitraire ?
=> SQL - Add LIMIT 1 with ORDER BY distance  when intersecting point and parcelle

.docker/docker-compose-qgis.yml, CHANGELOG.md, gestion_base_adresse/metadata.txt, gestion_base_adresse/processing/data/data_parcelle.py, gestion_base_adresse/processing/data/load_layers.py, gestion_base_adresse/processing/data/refresh_view.py, gestion_base_adresse/processing/structure/create_database_structure.py, gestion_base_adresse/processing/structure/upgrade_database_structure.py, gestion_base_adresse/test/base_test_database.py
* Ticket : fix #144 en attente de validation suite au contact par mail
* Python - Remove support for QGIS 3.10
=> Python - Remove support for QGIS 3.10

.gitignore, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_1.2.0.sql, gestion_base_adresse/test/test_execute_functions.py
* SQL - Fix the view export_bal when there is a commune deleguee
=> SQL - Fix the view export_bal when there is a commune deleguee

CHANGELOG.md, gestion_base_adresse/install/sql/adresse/30_VIEW.sql, gestion_base_adresse/install/sql/adresse/70_COMMENT.sql, gestion_base_adresse/install/sql/upgrade/upgrade_to_1.2.1.sql, gestion_base_adresse/processing/data/data_parcelle.py, gestion_base_adresse/processing/data/load_styles.py, gestion_base_adresse/test/test_execute_functions.py
SQL - Fix duplicated entries in editable views
=> SQL - Fix duplicated entries in editable views
